document.addEventListener("DOMContentLoaded",()=>{
const bars=[0,0,0,0,0,0,0,0,0,0,0,0];
shell(`<div class="page-head"><div><div class="eyebrow">DECISION INTELLIGENCE</div><h1>Analytics & Reports</h1><p>Measure response performance, resource utilization and disaster trends.</p></div><div class="actions"><button class="btn btn-ghost" id="range">Last 30 days ▾</button><button class="btn btn-primary" id="report">Generate Report</button></div></div>
<div class="kpi-grid"><div class="kpi"><div class="kpi-head"><span>Cases Resolved</span><span>+8.2%</span></div><div class="kpi-value success-text">0</div><div class="kpi-change">No records available</div></div><div class="kpi"><div class="kpi-head"><span>Avg Response</span><span>0</span></div><div class="kpi-value">0</div><div class="kpi-change success-text">No response data</div></div><div class="kpi"><div class="kpi-head"><span>Resources Used</span><span>Efficiency</span></div><div class="kpi-value">0%</div><div class="kpi-change">No resource data</div></div><div class="kpi"><div class="kpi-head"><span>Lives Assisted</span><span>30 days</span></div><div class="kpi-value">0</div><div class="kpi-change success-text">No activity recorded</div></div></div>
<div class="grid-2"><div class="panel"><div class="panel-head"><h3>Response Volume</h3><span>12-period trend</span></div><div class="chart">${bars.map((v,i)=>`<div class="bar" style="height:${v}%"><span>${i+1}</span></div>`).join("")}</div></div><div class="panel"><div class="panel-head"><h3>Disaster Mix</h3></div><div class="panel-body" style="display:grid;grid-template-columns:1fr 1fr"><div class="donut-wrap"><div class="donut"><div class="donut-label">0</div></div></div><div class="legend"><span class="d">Flood — 0%</span><span class="w">Landslide — 0%</span><span class="i">Fire — 0%</span><span class="s">Other — 0%</span></div></div></div></div>
<div class="grid-3"><div class="panel"><div class="panel-head"><h3>Response SLA</h3></div><div class="panel-body"><div class="stat-line"><span>Critical &lt; 15 min</span><b>0%</b></div><div class="progress"><span style="width:0%"></span></div><div class="stat-line" style="margin-top:14px"><span>High &lt; 30 min</span><b>0%</b></div><div class="progress"><span style="width:0%"></span></div></div></div><div class="panel"><div class="panel-head"><h3>Top Resource Demand</h3></div><div class="panel-body"><div class="stat-line"><span>Water</span><b>0%</b></div><div class="stat-line"><span>Food</span><b>0%</b></div><div class="stat-line"><span>Medical</span><b>0%</b></div><div class="stat-line"><span>Shelter</span><b>0%</b></div></div></div><div class="panel"><div class="panel-head"><h3>Risk Index</h3></div><div class="panel-body"><div style="font-size:42px;font-weight:900;color:var(--warning)">0<span style="font-size:14px;color:var(--muted)"> / 100</span></div><p class="muted" style="font-size:10px">High operational risk based on current simulated conditions.</p></div></div></div>
<div class="panel" style="margin-top:12px"><div class="panel-head"><h3>Performance by Zone</h3><span>Current period</span></div><div class="table-wrap"><table class="data-table"><thead><tr><th>ZONE</th><th>INCIDENTS</th><th>RESPONSE</th><th>RESOLUTION</th><th>RESOURCES</th><th>RISK</th></tr></thead><tbody><tr><td>Dehradun Valley</td><td>84</td><td>10.2m</td><td>0%</td><td>71%</td><td>${severity("HIGH")}</td></tr><tr><td>Mussoorie Hills</td><td>38</td><td>14.8m</td><td>89%</td><td>82%</td><td>${severity("CRITICAL")}</td></tr><tr><td>Rishikesh Corridor</td><td>26</td><td>11.3m</td><td>92%</td><td>64%</td><td>${severity("MEDIUM")}</td></tr></tbody></table></div></div>`);
document.getElementById("range").onclick=()=>toast("Date range","Analytics range changed to the last 30 days.");document.getElementById("report").onclick=()=>{let t="Disaster Management And Rescue System (DMRS) Analytics Report\\n\\nCases resolved: 0\\nAverage response: 12.4 min\\nResources used: 0%\\nLives assisted: 0";let a=document.createElement("a");a.href=URL.createObjectURL(new Blob([t],{type:"text/plain"}));a.download="resq-analytics-report.txt";a.click();toast("Report generated","Executive report exported.")};
});
