document.addEventListener("DOMContentLoaded",()=>{
shell(`<div class="page-head"><div><div class="eyebrow">LIVE SITUATIONAL AWARENESS</div><h1>Command Dashboard</h1><p>No records have been added yet. Use the modules to create your first entries.</p></div><div class="actions"><button class="btn btn-danger" id="broadcast">⚠ Emergency Broadcast</button><button class="btn btn-primary" id="newIncident">+ New Incident</button></div></div>
<div class="kpi-grid"><div class="kpi"><div class="kpi-head"><span>Active Disasters</span><span>LIVE</span></div><div class="kpi-value danger-text">0</div><div class="kpi-change">No disaster records</div></div><div class="kpi"><div class="kpi-head"><span>Emergency Reports</span><span>24H</span></div><div class="kpi-value">0</div><div class="kpi-change">No emergency reports</div></div><div class="kpi"><div class="kpi-head"><span>Response Teams</span><span>NETWORK</span></div><div class="kpi-value">0</div><div class="kpi-change">No teams registered</div></div><div class="kpi"><div class="kpi-head"><span>Resources</span><span>INVENTORY</span></div><div class="kpi-value">0</div><div class="kpi-change">No resource records</div></div></div>
<div class="grid-2"><div class="panel"><div class="panel-head"><h3>Incident Activity</h3><span>Current records</span></div><div class="panel-body"><div class="empty"><b>No incident activity</b>Activity will appear after records are added.</div></div></div><div class="panel"><div class="panel-head"><h3>Severity Distribution</h3><span>Active incidents</span></div><div class="panel-body"><div class="empty"><b>0 active incidents</b>No severity data available.</div></div></div></div>
<div class="grid-2"><div class="panel"><div class="panel-head"><h3>Critical Incident Queue</h3><a href="emergencies.html">View all →</a></div><div class="panel-body"><div class="empty"><b>No incidents</b>Emergency reports will appear here.</div></div></div><div class="panel"><div class="panel-head"><h3>Resource Readiness</h3><a href="resources.html">Manage →</a></div><div class="panel-body"><div class="empty"><b>No resources recorded</b>Add inventory to track readiness.</div></div></div></div>`);
document.getElementById("newIncident").onclick=()=>location.href="emergencies.html?new=1";
document.getElementById("broadcast").onclick=()=>openModal("Emergency Broadcast",`<div class="form-grid"><div class="form-field"><label>ALERT TITLE</label><input id="btitle"></div><div class="form-field"><label>AFFECTED AREA</label><input id="barea"></div><div class="form-field"><label>SEVERITY</label><select id="bsev"><option>CRITICAL</option><option>HIGH</option><option>MEDIUM</option></select></div><div class="form-field full"><label>PUBLIC MESSAGE</label><textarea id="bmsg"></textarea></div></div>`,`<button class="btn btn-ghost" data-close>Cancel</button><button class="btn btn-primary" id="sendBroadcast">Send Broadcast</button>`);
document.getElementById("sendBroadcast")?.addEventListener("click",()=>{closeModal();toast("Broadcast queued","Demo broadcast prepared.","warning")});
});
