document.addEventListener("DOMContentLoaded",()=>{
shell(`<div class="page-head"><div><div class="eyebrow">GEO-SPATIAL OPERATIONS</div><h1>Live Operations Map</h1><p>Situational view of incidents, teams, hospitals, shelters and assets.</p></div><div class="actions"><button class="btn btn-ghost" id="locate">⌖ Locate command center</button><button class="btn btn-primary" id="mark">+ Mark Incident</button></div></div>
<div class="panel"><div class="map-large" id="opsMap"><div class="map-controls"><button id="zin">+</button><button id="zout">−</button><button id="reset">⌂</button></div><div class="map-legend"><span><i></i> Incident</span><span class="lg-w"><i></i> Team</span><span class="lg-s"><i></i> Facility</span></div>
<div class="map-marker" style="left:22%;top:32%" data-info="Flood · Clement Town"><div class="marker-dot danger"></div><span class="marker-label">Flood / Critical</span></div>
<div class="map-marker" style="left:47%;top:45%" data-info="Rescue Alpha · Mussoorie"><div class="marker-dot warning"></div><span class="marker-label">Rescue Alpha</span></div>
<div class="map-marker" style="left:66%;top:58%" data-info="District Emergency Hospital"><div class="marker-dot"></div><span class="marker-label">Hospital</span></div>
<div class="map-marker" style="left:74%;top:27%" data-info="Shelter · Raipur"><div class="marker-dot"></div><span class="marker-label">Shelter</span></div>
<div class="map-marker" style="left:38%;top:70%" data-info="Landslide · Library Chowk"><div class="marker-dot danger"></div><span class="marker-label">Landslide</span></div>
<div class="map-marker" style="left:82%;top:72%" data-info="Medical Response Team"><div class="marker-dot warning"></div><span class="marker-label">Medical Team</span></div>
</div></div>
<div class="grid-3"><div class="panel"><div class="panel-head"><h3>Map Layers</h3></div><div class="panel-body"><label class="check"><input type="checkbox" checked> Incidents</label><label class="check" style="margin-top:10px"><input type="checkbox" checked> Response teams</label><label class="check" style="margin-top:10px"><input type="checkbox" checked> Hospitals</label><label class="check" style="margin-top:10px"><input type="checkbox" checked> Shelters</label></div></div><div class="panel"><div class="panel-head"><h3>Risk Overlay</h3></div><div class="panel-body"><div class="progress danger"><span style="width:82%"></span></div><p class="muted" style="font-size:10px;margin-top:8px">High-risk flood exposure: 82%</p></div></div><div class="panel"><div class="panel-head"><h3>Nearest Resources</h3></div><div class="panel-body"><div class="stat-line"><span>Rescue team</span><b>4.2 km</b></div><div class="stat-line"><span>Hospital</span><b>6.1 km</b></div><div class="stat-line"><span>Shelter</span><b>2.4 km</b></div></div></div></div>`);
document.querySelectorAll(".map-marker").forEach(x=>x.onclick=()=>toast("Map location",x.dataset.info));
let z=1;const map=document.getElementById("opsMap");document.getElementById("zin").onclick=()=>{z=Math.min(1.6,z*1.15);map.style.backgroundSize=55*z+"px "+55*z+"px"};document.getElementById("zout").onclick=()=>{z=Math.max(.7,z*.87);map.style.backgroundSize=55*z+"px "+55*z+"px"};document.getElementById("reset").onclick=()=>{z=1;map.style.backgroundSize="55px 55px"};document.getElementById("locate").onclick=()=>toast("Command center","Reference point: Dehradun control room.");document.getElementById("mark").onclick=()=>toast("Map action","Use the incident form to create a persistent geospatial report.","warning");
});
